# Generated by Django 4.0.6 on 2022-07-22 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoTables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_table', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('todo_tables', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.todotables')),
            ],
        ),
    ]
